// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJPd-dF2oCXe5CdjPo0ehU9w88Xi3V_Jc',
    appId: '1:201132848874:web:d06c494b89214476424993',
    messagingSenderId: '201132848874',
    projectId: 'responsive-design-59d8f',
    authDomain: 'responsive-design-59d8f.firebaseapp.com',
    storageBucket: 'responsive-design-59d8f.firebasestorage.app',
    measurementId: 'G-E0MPRQ0DKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbCNDIO3tpyLotljIoyuhzQ4Gv6G0mWZs',
    appId: '1:201132848874:android:7b2bf36ffa6ad861424993',
    messagingSenderId: '201132848874',
    projectId: 'responsive-design-59d8f',
    storageBucket: 'responsive-design-59d8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaTUYebNKFHhVggWLqGQN5CdjuSNzwK1g',
    appId: '1:201132848874:ios:0b6fcb0d2bb3659c424993',
    messagingSenderId: '201132848874',
    projectId: 'responsive-design-59d8f',
    storageBucket: 'responsive-design-59d8f.firebasestorage.app',
    iosBundleId: 'com.example.responsiveDesign',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaTUYebNKFHhVggWLqGQN5CdjuSNzwK1g',
    appId: '1:201132848874:ios:0b6fcb0d2bb3659c424993',
    messagingSenderId: '201132848874',
    projectId: 'responsive-design-59d8f',
    storageBucket: 'responsive-design-59d8f.firebasestorage.app',
    iosBundleId: 'com.example.responsiveDesign',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJPd-dF2oCXe5CdjPo0ehU9w88Xi3V_Jc',
    appId: '1:201132848874:web:c92501bc8fa3564a424993',
    messagingSenderId: '201132848874',
    projectId: 'responsive-design-59d8f',
    authDomain: 'responsive-design-59d8f.firebaseapp.com',
    storageBucket: 'responsive-design-59d8f.firebasestorage.app',
    measurementId: 'G-Z50MLE5Q2Z',
  );
}
