import 'package:flutter/material.dart';
import 'profile_card.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI

// This is the entry point of the application. It initializes Firebase and runs the app before anything else.
void main() async { // asynchronous means we can use await inside this function
  WidgetsFlutterBinding.ensureInitialized(); // ensures Flutter is ready before Firebase init (login service)
  await Firebase.initializeApp( // await means we wait for this to complete before moving on
    options: DefaultFirebaseOptions.currentPlatform,
  );
  print("Firebase initialized successfully!"); 
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Responsive Design',
      home: const ProfileCard(),
    );
  }
}
